version: "3.8"

services:
    database:
        command: --max-allowed-packet=64MB
        container_name: api-database
        image: mysql
        environment:
            MYSQL_ROOT_PASSWORD: password
            MYSQL_DATABASE: api-database
        volumes:
            - data:/var/lib/mysql
        networks:
            - dev

    adminer:
        container_name: api-adminer
        image: adminer
        ports:
            - 8081:8080
        networks:
            - dev
        depends_on:
            - database

    web:
        container_name: api-web
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - 8080:80
        volumes:
            - ./:/var/www
        networks:
            - dev
        depends_on:
            - database


volumes:
    data:

networks:
    dev: